name: Build site

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:

  buildsite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy Nikola to GitHub Pages
      uses: getnikola/nikola-action@v8
